### ISSUE TITLE
Release code please

### ISSUE THREAD

**Issue by LLLiuTC** [alfredgu001324/MapUncertaintyPrediction#1]
Hello, I appreciated your great work and  got very interesed in your work. I can't wait to see what you actually do in this code. I would be very appreciative if you could release the code soon.

**Comment by alfredgu001324** [comment]
Thank you so much for your interest in our work!! Unfortunately I am caught up with my capstone project and exams right now. If you can send me an email, I am happy to send you the less 'tidy-up' code and provide some rough instructions.
