### ISSUE TITLE
Bug in Merging Map Data with Trajectory Data(no predicted_map)

### ISSUE THREAD

**Issue by zhepanqi** [alfredgu001324/MapUncertaintyPrediction#10]
when i ran adaptor.py,it just couldn't generate the predicted_map,which is   needed in the training of HiVT,and this really confused me. I wonder if you once encounter the problem like this. Really hope i can get some help from you.
![image](https://github.com/user-attachments/assets/d791d1af-b427-4189-af44-6c01a1d6c5f1)
![image](https://github.com/user-attachments/assets/bcb98bf3-aa0e-490f-8e3d-6db5177546aa)

**Comment by zhepanqi** [comment]
When running HiVT, I encountered an error indicating that predicted_map was missing. Therefore, I added two lines of code in adaptor.py to check if this component exists in the generated map, and the result showed that it does not.
![image](https://github.com/user-attachments/assets/e4a2c0e5-d9f6-4918-a82e-6eaa0796ca94)
![image](https://github.com/user-attachments/assets/c1e4598a-ffde-4572-b5da-d4569880216e)

**Comment by alfredgu001324** [comment]
Thanks for pointing this out! 

The first thing I noticed is that the MapTR GT file should also be on the full val set, so the two progress bars should have the same counts. 

Can I take a look at the command you run? I wonder if there are any file mismatches here. Just FYI, there are indeed some missing frame infos since trajdata cannot fully capture all the frames. This is why there is a try except block there. However the missing data should not be too much. After filtering out this missing info, and the frames that do not have future and history (which is the majority of filtering), the # of scenes in full_val should be 4519 -> so 4519 valid scenarios out of 6019 frames.

**Comment by zhepanqi** [comment]
thank you so much for helping me,this is the code i ran

python adaptor.py \
  --version mini \
  --split mini_train \
  --map_model MapTR \
  --dataroot ../nuscenes \
  --index_file ../adaptor_files/traj_scene_frame_mini_train.pkl \
  --map_file ../mapping_results.pickle \
  --gt_map_file ../adaptor_files/gt_mini_val.pickle \
  --save_path ../trj_data/maptrv2

**Comment by alfredgu001324** [comment]
It should be `--gt_map_file ../adaptor_files/gt_mini_train.pickle`. Also, from your progress bar it seems that your `mapping_results.pickle` contains the estimated map of full val set, which does not match what you specified here (mini train).

**Comment by zhepanqi** [comment]
I'm sorry, but there is no gt_mini_train.pkl file in your cloud drive, so we chose to use val instead.

**Comment by zhepanqi** [comment]
and if i run the command like this, the same problem occur
python adaptor.py \
  --version trainval \
  --split train \
  --map_model MapTR \
  --dataroot ../nuscenes \
  --index_file ../adaptor_files/traj_scene_frame_full_val.pkl \
  --map_file ../mapping_results.pickle \
  --gt_map_file ../adaptor_files/gt_full_val.pickle \
  --save_path ../trj_data/maptrv2

**Comment by alfredgu001324** [comment]
Uh I see, sorry for the oversight. I probably thought mini train is not as important so did not put it up. 

As for your second command, the split should be val I guess (instead of train)?

**Comment by zhepanqi** [comment]
I'm very sorry to bother you multiple times. Actually, we are running the correct code, but we made a mistake in the comments section. Here is the part I re-ran, and you can see that this time I have used the complete dataset, but the issue of missing predicted_map still occurs. 
tags: f'nusc trainval-boston-train''singapore-nusc trainval-tra].
Calculating Agent Data(serially): 100%500 scenes in the scene index.Creating scene Data Index(4 CPUs): 100%Index: 100%Structuring scene Data#
<img width="325" alt="2480b93ea37e9a5423c5e549e030e4c" src="https://github.com/user-attachments/assets/0ef86ae3-75ee-4db5-bd51-e0360206da39">

Moreover, in the training of HiVT, we are also unable to proceed due to this issue.
<img width="468" alt="79476fb70dd40f6ecdfd64f3d692216" src="https://github.com/user-attachments/assets/8425ee9d-64b4-42d6-9298-f08b24fb00fd">
<img width="472" alt="8df46086b2ddd0b919a6aa13fd538f2" src="https://github.com/user-attachments/assets/6bd1776d-3884-4c35-bfec-3ab2abe2da62">

**Comment by alfredgu001324** [comment]
No problem at all! The command looks good to me. I just tried re-running on my side but it seems to be fine. To debug, can you maybe try running this on val only, and see whether val has this problem? or maybe on the mini_val set.

**Comment by zhepanqi** [comment]
Thank you very much for your perfect work and your patient responses. This has been very helpful for us, and we have almost successfully replicated some of your results. However, I would like to point out that not all data in `adaptor.py` can generate `predicted_map`. I suggest adding a filtering feature before saving the processed data, otherwise there will be errors during the subsequent HiVT model training.

**Comment by JT-Sun** [comment]
> Thank you very much for your perfect work and your patient responses. This has been very helpful for us, and we have almost successfully replicated some of your results. However, I would like to point out that not all data in `adaptor.py` can generate `predicted_map`. I suggest adding a filtering feature before saving the processed data, otherwise there will be errors during the subsequent HiVT model training.

Hello, I have the same problem with you. How did you solve it and successfully train HiVT?

**Comment by zhepanqi** [comment]
> > Thank you very much for your perfect work and your patient responses. This has been very helpful for us, and we have almost successfully replicated some of your results. However, I would like to point out that not all data in `adaptor.py` can generate `predicted_map`. I suggest adding a filtering feature before saving the processed data, otherwise there will be errors during the subsequent HiVT model training.
> 
> Hello, I have the same problem with you. How did you solve it and successfully train HiVT?

As I said before, add a filter before saving the ultimate data to make sure predicted_map exist may help you.

**Comment by alfredgu001324** [comment]
For debugging, can you maybe retrieve a sample token that corresponds to a pissing 'predicted_map', and then go back to mapping_results.pkl to see if there is any predicted map information corresponding to that sample token? As a reference, if things go smoothly this will generate a total of 15191 scenario files for full train.

**Comment by alfredgu001324** [comment]
Please refer to https://github.com/alfredgu001324/MapUncertaintyPrediction/issues/4 and https://github.com/alfredgu001324/MapUncertaintyPrediction/issues/13
