### ISSUE TITLE
two question on visualization of map estimation

### ISSUE THREAD

**Issue by Chenqingsu1** [alfredgu001324/MapUncertaintyPrediction#11]
Q①How can I find the actual photos corresponding to each sample_idx in maptr?
Q②In the visualization of the map estimation model in the paper, there are "car" elements, but these are not included in mapping_results.pkl. How can I visualize the "car" elements as well?

<img width="928" alt="0b8631c6fc25885644c1fd3cbfe35aa" src="https://github.com/user-attachments/assets/aaf3a1bd-1146-46fb-88e7-96951ed9c5e3">

**Comment by Chenqingsu1** [comment]
![image](https://github.com/user-attachments/assets/ec70cde0-ace7-4945-aa9f-89c1cc2fe686)
Visualization of PKL as shown in the figure

**Comment by alfredgu001324** [comment]
Thanks for reaching out!

Q1. A good question actually, I remember I did have some code to retrieve the images. But due to some file management issue I lost that part of the code, but I still have the image files stored locally so I just directly access it from my local folder (sorry). But in MapTR's code, specifically this [for loop](https://github.com/hustvl/MapTR/blob/fa420a2e756c9e19b876bdf2f6d33a097d84be73/tools/maptr/vis_pred.py#L244), I believe it is used for accessing the images. Maybe you can add that to the current visualization script you have. 

Q2. Yes, you can refer to the [visualization instructions ](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/visualization.md)I have. In there I put the bboxes file as well that you can use.

**Comment by Chenqingsu1** [comment]
> 感谢您的联系！
> 
> Q1. 其实这是一个好问题，我记得我确实有一些代码来检索图像。但由于一些文件管理问题，我丢失了这部分代码，但我仍然将图像文件存储在本地，因此我只需直接从本地文件夹访问它（抱歉）。但在 MapTR 的代码中，特别是这个[for 循环](https://github.com/hustvl/MapTR/blob/fa420a2e756c9e19b876bdf2f6d33a097d84be73/tools/maptr/vis_pred.py#L244)，我相信它是用于访问图像的。也许你可以将其添加到你当前的可视化脚本中。
> 
> Q2. 是的，您可以参考我的[可视化说明](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/visualization.md)。我在其中也放了 bboxes 文件，您可以使用。

Thank you for the above answer. sry to bother you, I have one more question : specifically, which pkl file is loaded for the visualization of GT?I loaded the gt_full_val.pickle file, but it does not contain "bbox".
![image](https://github.com/user-attachments/assets/314e6aa1-818d-4d48-b5e0-e2f869eb407b)

**Comment by Chenqingsu1** [comment]
> Thanks for reaching out!
> 
> Q1. A good question actually, I remember I did have some code to retrieve the images. But due to some file management issue I lost that part of the code, but I still have the image files stored locally so I just directly access it from my local folder (sorry). But in MapTR's code, specifically this [for loop](https://github.com/hustvl/MapTR/blob/fa420a2e756c9e19b876bdf2f6d33a097d84be73/tools/maptr/vis_pred.py#L244), I believe it is used for accessing the images. Maybe you can add that to the current visualization script you have.
> 
> Q2. Yes, you can refer to the [visualization instructions ](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/visualization.md)I have. In there I put the bboxes file as well that you can use.

Thank you for the above answer. sry to bother you, I have one more question : specifically, which pkl file is loaded for the visualization of GT?I loaded the gt_full_val.pickle file, but it does not contain "bbox".

**Comment by alfredgu001324** [comment]
Yes, gt_full_val.pickle only contains the gt map information. The bbox information download link is in the visualization page. But maybe you are right, I should put them together to avoid confusion.

**Comment by Chenqingsu1** [comment]
Sorry to bother you. May I ask if the corresponding real images in your visualization demo need to be downloaded separately? I'm not sure about the source of the real images.

**Comment by alfredgu001324** [comment]
Sorry for the lat response. They are part of the nuscenes dataset, you should be able to find them based on the file name path in the image metas.
