### ISSUE TITLE
IndexError: too many indices for array: array is 3-dimensional, but 4 were indexed

### ISSUE THREAD

**Issue by Chenqingsu1** [alfredgu001324/MapUncertaintyPrediction#14]
python vis_std2.py --version mini --dataroot ../nuscenes --split val --trj_pred HiVT --map MapTR --trj_data ../trj_data/maptrv2/val_1/data --base_results /MapUncertaintyPrediction-main/HiVT_modified/result_maptrv2_base.pkl --unc_results /MapUncertaintyPrediction-main/HiVT_modified/result_maptrv2_unc.pkl --boxes /MapUncertaintyPrediction-main/HiVT_modified/bbox.pkl --save_path /MapUncertaintyPrediction-main/HiVT_modified/vis_files

This is the command I executed, but I got this error.
<img width="385" alt="0bf58a5982ff0c5153092e9e6ecc924" src="https://github.com/user-attachments/assets/6a0cbb1a-4cd7-4038-812a-ee2e830095be">
I tried to output the matrix shape of hivt trj, and it showed (6, 20, 4).

Why does this error occur, and how can I fix it?
thanks，I'm afraid to modify the code randomly.🥲

**Comment by alfredgu001324** [comment]
Hi, can you maybe double check how you obtain hivt trj? It should be in 3 seconds, but yours is in 2 seconds, seems like the history to me. 

Also, split should be mini_val when specifying version to be mini

**Comment by Chenqingsu1** [comment]
python eval.py \
  --root ../trj_data/maptrv2 \
  --split val \
  --method base\
  --batch_size 32 \
  --ckpt_path /data15/chenjh2309/Zhangboran/MapUncertaintyPrediction-main/HiVT_modified/maptrv2_base.ckpt

I executed test.py and obtained results.pkl
<img width="608" alt="910f9f37bd5272815f8f2ce0c419454" src="https://github.com/user-attachments/assets/98fe9d8f-945a-4436-842f-34988b6cb6e0">

And used it as the base_results parameter in the visualization command.
<img width="525" alt="85df0f1c8e19fa56dc672266f4ff19c" src="https://github.com/user-attachments/assets/deae2a55-a28c-400c-81a3-bec28ea8395b">

**Comment by alfredgu001324** [comment]
To debug, maybe look at what this [line](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/8ab64116982303d373eb85fea2501e139a09e781/HiVT_modified/models/hivt.py#L138) outputs?
