### ISSUE TITLE
no goals_2D(evaluation of DenseTNT)

### ISSUE THREAD

**Issue by zhepanqi** [alfredgu001324/MapUncertaintyPrediction#15]
Hello,
It's me again. We have just completed the training of your HiVT model and successfully achieved the results. We are now working on the training of DenseTNT. Could you please confirm if you are still using the files generated by adaptor.py from the Nuscenes dataset (the same as for HiVT)? Additionally, why does your train_and_eval.sh script include 'goals_2D' in the other_params? Shouldn't this be a parameter for the Argoverse dataset? It seems that training with this setup may not allow for proper evaluation in the end.

**Comment by alfredgu001324** [comment]
Thank you so much for your work and confirmation!! In terms of DenseTNT training, yes we are still using the same files as in HiVT. In terms of specific training, I might need to consult with my collaborator and let you know later.

**Comment by songguanyu** [comment]
> Hello, It's me again. We have just completed the training of your HiVT model and successfully achieved the results. We are now working on the training of DenseTNT. Could you please confirm if you are still using the files generated by adaptor.py from the Nuscenes dataset (the same as for HiVT)? Additionally, why does your train_and_eval.sh script include 'goals_2D' in the other_params? Shouldn't this be a parameter for the Argoverse dataset? It seems that training with this setup may not allow for proper evaluation in the end.

Hi Guantian, thank you for the comment. "goals_2D" refers to the goal-based strategy densetnt utilizes to predict the trajectories. DenseTNT estimates the goals (end positions) of agents' future trajectory and then generates the complete trajectory based on the goals. There do be some redundant arguments in the script but none of them should affect anything. I will also clean it up a little bit shortly.
