### ISSUE TITLE
Not on the test.py. Just edit the config file's evaluation path to evaluate on the training set as well.

### ISSUE THREAD

**Issue by DrinkLego** [alfredgu001324/MapUncertaintyPrediction#18]
Not on the test.py. Just edit the config file's evaluation path to evaluate on the training set as well.

_Originally posted by @alfredgu001324 in https://github.com/alfredgu001324/MapUncertaintyPrediction/issues/13#issuecomment-2237185916_

**Comment by DrinkLego** [comment]
Sorry to bother you, I’m not very familiar with GitHub yet. I would like to know specifically where in the config file to modify in order to change the evaluation path

**Comment by DrinkLego** [comment]
I modified the file located at `MapTR_modified/projects/configs/maptr/maptr_tiny_r50_24e.py`, changing the path of ann_file, but an error occurred.
![image](https://github.com/user-attachments/assets/79fe3edb-2d31-4926-82f3-f17fb49b1f23)

![image](https://github.com/user-attachments/assets/b79e0224-8389-4f04-9ee5-517141cc0d43)

**Comment by alfredgu001324** [comment]
Thank you for your interest in our work and sorry for the late response (just finished my summer internship and have time to look into this)! 

Do you still see this issue at the moment? What command are you trying to run?

**Comment by DrinkLego** [comment]
I have resolved this issue. Thank you again for your response!
