### ISSUE TITLE
Question about Map Uncertainty

### ISSUE THREAD

**Issue by Still-Wang** [alfredgu001324/MapUncertaintyPrediction#19]
Taking MapTR2's consideration of uncertainty as an example, I have currently only found changes in the loss_pts configuration in the project code:
`# loss_pts=dict(type='PtsL1Loss', 
#               loss_weight=5.0),
loss_pts=dict(type='PtsNLLLoss', 
              loss_weight=0.03),`
So, where is the statement in the paper, 'we replace the regression head with one that additionally outputs uncertainty parameters associated with the predicted points,' reflected in the code?"
hope for your reply.thanks!

**Comment by alfredgu001324** [comment]
Thank you for your interest in our work! The modification is [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/08baf647b8fb7d20cb2840ed8996dd788cd38f3f/MapTRv2_modified/projects/mmdet3d_plugin/maptr/dense_heads/maptrv2_head.py#L78). For the other models the modification should be similar.

**Comment by Still-Wang** [comment]
Thank you for your thoughtful response. I will carefully study it.
