### ISSUE TITLE
calculation of ADE

### ISSUE THREAD

**Issue by Guanyi-Liu** [alfredgu001324/MapUncertaintyPrediction#20]
It seems that there is no calculation of ADE in your DenseTNT model, which leaves me quite confused.

**Comment by alfredgu001324** [comment]
Maybe somewhere [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/08baf647b8fb7d20cb2840ed8996dd788cd38f3f/DenseTNT_modified/src/do_eval.py#L118)?

**Comment by DrinkLego** [comment]
Hello, I would like to ask have you successfully evaluated `DenseTNT`? I encountered issues during the evaluation process, and it has been puzzling me for a long time. If so, how did you solve it? THANKS!

**Comment by alfredgu001324** [comment]
@DrinkLego I think there might be two missing arguments ( --argoverse --argoverse2). I found these arguments in my script but not in the github repo. Can you add these and try?

**Comment by Guanyi-Liu** [comment]
Yes, indeed, there are two missing parameters in the source file, which prevents the code from running properly.
At the same time, I would also like to ask, what method is used in DenseTNT to differentiate between base and unc during training? In HiVT, we use method for distinction, but I haven’t found a similar method in DenseTNT.

**Comment by alfredgu001324** [comment]
Good point, let me take a quick look. Sorry my collaborator took care of this part so I am not too sure.

**Comment by Guanyi-Liu** [comment]
I'm sorry I kept looking for it in the argparse parameters and didn't notice the function itself. Thank you so much for your patient explanation.

**Comment by alfredgu001324** [comment]
No problem at all! Sorry for the bad documentation ....
