### ISSUE TITLE
mapping_results.pickle from mapping evaluation

### ISSUE THREAD

**Issue by sharmasushil** [alfredgu001324/MapUncertaintyPrediction#23]
Hi,
Great work!

I was wondering where I can find the mapping_results.pickle file. In the downloaded files, I only see the Trajdata pickle and ground truth files. I know this might seem like a small detail, but it’s important.

Thanks

**Comment by alfredgu001324** [comment]
Thank you for your interest in our work! You need to generate the mapping_results.pickle by evaluating on those mapping models. They are the evaluation results of the mapping stage. 

Hope that helps!

**Comment by sharmasushil** [comment]
Thanks, Really Appreciate for your help
