### ISSUE TITLE
About the method of DenseTNT prediction

### ISSUE THREAD

**Issue by HB1109** [alfredgu001324/MapUncertaintyPrediction#26]
Hello, I have trained and tested the map, and completed the merging, how to train DenseTNT

**Comment by alfredgu001324** [comment]
Thank you for your interest in our work! [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/DenseTNT_modified/train_and_eval.sh) is a script that you can use to do the training. 

And if I remember correctly, you can modify [this line](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/08baf647b8fb7d20cb2840ed8996dd788cd38f3f/DenseTNT_modified/src/dataset_nuscene.py#L43) to select whether you use the uncertainty input or not.

Hope this helps!

**Comment by HB1109** [comment]
I encountered the "predicted_map" missing, I read your previous solution, but I don't quite understand, scene-15190.pkl is complete in my code. Could you be a little more specific
The command I'm running is‘’
epochs=10
batch=16
lr=0.0005
dropout=0.1
output_dir="" # output_dir where model is stored
train_dir=/home/data/HiVT_stream/train/data/ # train data dir
val_dir=/home/data/HiVT_stream/val/data/ # val data dir
python src/run.py --nuscenes --future_frame_num 30 --do_train --data_dir $train_dir --data_dir_for_val $val_dir --output_dir $output_dir --hidden_size 128 --train_batch_size $batch --use_map --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj complete_traj-3 --eval_params optimization MRminFDE=0.0 cnt_sample=9 opti_time=0.1 --learning_rate $lr --hidden_dropout_prob $dropout --num_train_epochs $epochs
for i in {1..$epochs}
do
  echo $(python src/run.py --nuscenes --future_frame_num 30 --do_eval --data_dir $train_dir --data_dir_for_val $val_dir --output_dir $output_dir --hidden_size 128 --train_batch_size $batch --use_map --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj complete_traj-3 --eval_params optimization MRminFDE=0.0 cnt_sample=9 opti_time=0.1 --learning_rate $lr --hidden_dropout_prob $dropout --model_recover_path $i) >> $output_dir/eval_results
done
‘’I only changed the path

**Comment by alfredgu001324** [comment]
Uhmm The command seems to be right. Although I usually separate the training and val command and don't run them altogether, but it's no big issue. 

You mentioned that the pkl file is complete, but the `predicted_map` is still missing, is that the case?

**Comment by HB1109** [comment]
Right, that's it.Could you please specify the DenseTNT training method? I tried many times, but it didn't work, and I got the error "do.
echo $(python src/run.py --nuscenes --future_frame_num 30 --do_eval --data_dir $train_dir --data_dir_for_val $val_dir  --output_dir $output_dir --hidden_size 128 --train_batch_size $batch --use_map --core_num 16 --use_centerline  --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D enhance_global_graph subdivide  goal_scoring laneGCN point_sub_graph lane_scoring complete_traj complete_traj-3 --eval_params optimization MRminFDE=0.0 cnt_sample=9 opti_time=0.1 --learning_rate $lr --hidden_dropout_prob $dropout --model_recover_path $i) >> $output_dir/eval_results
"done" is not enough. I can run DenseTNT's original code in its entirety. Please advise me

**Comment by alfredgu001324** [comment]
That command is used for evaluation, can you maybe try this for training: https://github.com/alfredgu001324/MapUncertaintyPrediction/issues/17#issuecomment-2368291481

I think it is missing two arguments, sorry I haven't had time to make the edits in the repo.

**Comment by HB1109** [comment]
Ok, I'll try again. Thank you very much.

**Comment by HB1109** [comment]
Hello, I put the val training set of map and uncertainty fusion under the path of train to train DenseTNT normally. Run the script as follows:train_dir=/home/data/HiVT_stream/val/data/ # train data dir
val_dir=/home/data/HiVT_stream/val/data/ # val data dir
python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /root/autodl-tmp/MapUncertaintyPrediction/trj_data/maptr/mini_train/data - --output_dir /root/autodl-tmp/MapUncertaintyPrediction/DenseTNT_modified/model --hidden_size 128 --train_batch_size 8 --use_map --core_num 8 --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj complete_traj-3 
When I merged trian, I found that there was no 'gt_mini_train.pickle'. I think the KeyError: "predicted_map" is related to the absence of this pickle file. Or, when I evaluated the map, I only evaluated it once. When I looked at the previous answers to other people's questions, I couldn't find a method to evaluate the map twice. I only generated a mapping_results.pickle file. Could you please specify the method of evaluating the map twice? Thank you for your guidance, which has been very helpful to me.

**Comment by alfredgu001324** [comment]
Yes, there is no gt_mini_train.pickle as I thought that is unnecessary so did not generate it. Mini val should be enough for debugging purpose. 

To evaluate mapping models on other splits, basically you need to modify the paths that are associated with val, for example here: https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/08baf647b8fb7d20cb2840ed8996dd788cd38f3f/MapTRv2_modified/projects/configs/maptrv2/maptrv2_nusc_r50_24ep.py#L280

For trajectory prediction, you need to at least evaluate mapping models twice for each mapping method, once to generate train, and once to generate val. You can also evaluate one more time on the mini val split for debugging purpose. 

Hope that clarifies!

**Comment by HB1109** [comment]
Ok, your guidance is very useful to me. I will try it again. Thank you for your patience

**Comment by alfredgu001324** [comment]
No worries! Don't hesitate to reach out if anything is unclear.

**Comment by HB1109** [comment]
Ok, thank you for your guidance

**Comment by HB1109** [comment]
Sorry to bother you again. I don't quite understand what you said. "For trajectory prediction, you need to at least evaluate mapping models twice for each mapping method, once to generate train,  and once to generate val. You can also evaluate one more time on the mini val split for debugging  I have now completed the training and testing using the full dataset. In my test, I ran "source test.sh" only once. Whether I want to change the path after, Run "source test.sh" once to run ann_file=data_ann + 'nuscenes_map_infos_temporal_val.pkl', ann_file=data_ann + 'nuscenes_map_infos_temporal_train.pkl'?
But I ran "python adaptor.py \" in "Merging Map Data with Trajectory Data"
--version trainval \
--split val \
--map_model MapTR \
--dataroot /home/ps/Project/HB/nuscenes \
- index_file/home/ps/Project/HB/MapUncertaintyPrediction adaptor_files traj_scene_frame_full_train (val). PKL \
--map_file /home/ps/Project/HB/MapUncertaintyPrediction/adaptor_files/mapping_results.pickle\
- gt_map_file/home/ps/Project/HB/MapUncertaintyPrediction adaptor_files gt_full_train (val). Pickling \
- save_path/home/ps/Project/HB/MapUncertaintyPrediction trj_data/maptr run the "train" and "val.
But run "python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptr/train/data/  --output_dir  /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map  --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D  enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj  complete_traj-3" or prompt "Process process-16:
Traceback (most recent call last):
The File "/ home/ps/anaconda3 envs/predict/lib/python3.8 / multiprocessing/process. Py", line 315, in _bootstrap
self.run()
The File "/ home/ps/anaconda3 envs/predict/lib/python3.8 / multiprocessing/process. Py", line 108, in the run
self._target(*self._args, **self._kwargs)
File "/home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/src/dataset_nuscene.py", line 348, in calc_ex_list
instance = nuscene_get_instance(args, os.path.join(data_dir[0], file))
File "/home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/src/dataset_nuscene.py", line 53,  in nuscene_get_instance
vec_map = data['predicted_map']
KeyError: 'predicted_map'
". I run "python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptr/val/data/  --output_dir  /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map  --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D  enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj  complete_traj-3 "places val under the train path and can train normally.
What am I supposed to do, please

**Comment by HB1109** [comment]
Sorry to bother you again. I don't quite understand what you said. "For trajectory prediction, you need to at least evaluate mapping models twice for each mapping method, once to generate train,  and once to generate val. You can also evaluate one more time on the mini val split for debugging  I have now completed the training and testing using the full dataset. In my test, I ran "source test.sh" only once. I need to add ann_file=data_ann + 'nuscenes_map_infos_temporal_val.pkl', Does ann_file=data_ann + 'nuscenes_map_infos_temporal_train.pkl' run source test.sh once?
But I ran "python adaptor.py \" in "Merging Map Data with Trajectory Data"
--version trainval \
--split val \
--map_model MapTR \
--dataroot /home/ps/Project/HB/nuscenes \
- index_file/home/ps/Project/HB/MapUncertaintyPrediction adaptor_files traj_scene_frame_full_train (val). PKL \
--map_file /home/ps/Project/HB/MapUncertaintyPrediction/adaptor_files/mapping_results.pickle\
- gt_map_file/home/ps/Project/HB/MapUncertaintyPrediction adaptor_files gt_full_train (val). Pickling \
- save_path/home/ps/Project/HB/MapUncertaintyPrediction trj_data/maptr run the "train" and "val.
But run "python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptr/train/data/  --output_dir  /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map  --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D  enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj  complete_traj-3" or prompt "Process process-16:
Traceback (most recent call last):
The File "/ home/ps/anaconda3 envs/predict/lib/python3.8 / multiprocessing/process. Py", line 315, in _bootstrap
self.run()
The File "/ home/ps/anaconda3 envs/predict/lib/python3.8 / multiprocessing/process. Py", line 108, in the run
self._target(*self._args, **self._kwargs)
File "/home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/src/dataset_nuscene.py", line 348, in calc_ex_list
instance = nuscene_get_instance(args, os.path.join(data_dir[0], file))
File "/home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/src/dataset_nuscene.py", line 53,  in nuscene_get_instance
vec_map = data['predicted_map']
KeyError: 'predicted_map'
". I run "python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptr/val/data/  --output_dir  /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map  --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D  enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj  complete_traj-3 "places val under the train path and can train normally.

What should I do? Please provide me with more guidance.

**Comment by alfredgu001324** [comment]
Yes, that is correct. You need to run `source test.sh` twice, once on the training split, once on the validation split, so that you can have the map data necessary for training and evaluating downstream trajectory prediction models. 

I think it might be that you did not merge the map data and trj data successfully for the training split. When running the adaptor script, you need to change the `split` argument to either `train` or `val` for two different merging.

**Comment by HB1109** [comment]
Hello in the [Mapping Train and Eval] phase to evaluate the train and val data sets, is "ann_file=data_ann + 'nuscenes_infos_temporal_val.pkl',
map_ann_file=data_ann + 'nuscenes_map_anns_val.json', "is changed to ann_file=data_ann + 'nuscenes_infos_temporal_train.pkl',".
map_ann_file=data_ann + 'nuscenes_infos_temporal_train_mono3d.coco.json',”

**Comment by HB1109** [comment]
> 您好，我已经解决了测试问题。并已完成 DenseTNT 的培训。我想问一下 DenTNT 的 val 命令是否正确。运行以下命令： ppython src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --data_dir_for_val /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptrv2/val/data/ --output_dir /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane 方向 l1_loss goals_2D enhance_global_graph 细分goal_scoringlaneGCN point_sub_graph lane_scoring complete_traj complete_traj-3 --eval_params 优化 MRminFDE=0.0 cnt_sample=9 opti_time=0.1 --learning_rate 0.0005 --hidden_dropout_prob 0.1 --num_train_epochs 16”

1.DenseTNT training command: python src/run.py --nuscenes --argoverse --argoverse2 --future_frame_num 30 --do_train --data_dir /home/ps/Project/HB/MapUncertaintyPrediction/trj_data/maptrv2/train/data/  --output_dir  /home/ps/Project/HB/MapUncertaintyPrediction/DenseTNT_modified/mode --hidden_size 128 --train_batch_size 32 --use_map  --core_num 16 --use_centerline --distributed_training 1 --other_params semantic_lane direction l1_loss goals_2D  enhance_global_graph subdivide goal_scoring laneGCN point_sub_graph lane_scoring complete_traj complete_TRAj-3 "has completed the training. I run "train_and_eval.sh" and he can only train and cannot complete val, but I run the val command I sent above and cannot succeed val. Could you please send val's order? Could you please give me some guidance

**Comment by alfredgu001324** [comment]
Can you try the testing command here: https://github.com/alfredgu001324/MapBEVPrediction/blob/main/docs/trj.md

But ignore the `--method` argument. Sorry I should have updated this repo as well....

**Comment by HB1109** [comment]
Thank you, your work is perfect, I have successfully run through map train and val, and track prediction train and val. If there is a problem with the visualization behind, I need more trouble for you to guide me

**Comment by alfredgu001324** [comment]
Of course, no worries. Thanks for your support to our work!
