### ISSUE TITLE
Dataset Usage

### ISSUE THREAD

**Issue by HB1109** [alfredgu001324/MapUncertaintyPrediction#27]
Hello, much bother, can I use the nuscenes-mini data set for debugging?  I have tried to compile the data set with mini, but there will be a file missing error,  whether to modify part of the code, please kindly advise me

**Comment by alfredgu001324** [comment]
Yes, you can use the nuscenes-mini for debugging. May I know what command / file you are trying to run?

**Comment by HB1109** [comment]
I want to run the following command：python tools/create_data.py nuscenes --root-path ../nuscenes --out-dir ../processed/maptr --extra-tag nuscenes --version v1.0 --canbus ../nuscenes
But a missing file error will be reported.I want to change this "--version v1.0"
Looking forward to your reply, thank you

**Comment by HB1109** [comment]
Run the following script to compile the data set normally in 'MapTR_modified'：python /home/hb/project/MapUncertaintyPrediction/MapTR_modified/tools/create_data.py nuscenes --root-path /home/hb/project/MapUncertaintyPrediction/nuscenes --out-dir /home/hb/project/MapUncertaintyPrediction/processed/maptr --extra-tag nuscenes --version v1.0-mini --canbus /home/hb/project/MapUncertaintyPrediction/nuscenes
But run the following script ' python /home/hb/project/MapUncertaintyPrediction/MapTR_modified/tools/create_data.py nuscenes --root-path /home/hb/project/MapUncertaintyPrediction/nuscenes --out-dir /home/hb/project/MapUncertaintyPrediction/processed/maptr --extra-tag nuscenes --version v1.0-mini --canbus /home/hb/project/MapUncertaintyPrediction/nuscenes' in' MapTRv2_modified 'and get an error' Traceback (most recent call last):
  File "/home/hb/project/MapUncertaintyPrediction/MapTRv2_modified/tools/maptrv2/custom_nusc_map_converter.py", line 928, in <module>
    nuscenes_data_prep(
  File "/home/hb/project/MapUncertaintyPrediction/MapTRv2_modified/tools/maptrv2/custom_nusc_map_converter.py", line 869, in nuscenes_data_prep
    create_nuscenes_infos(
  File "/home/hb/project/MapUncertaintyPrediction/MapTRv2_modified/tools/maptrv2/custom_nusc_map_converter.py", line 777, in create_nuscenes_infos
    nusc = NuScenes(version=version, dataroot=root_path, verbose=True)
  File "/home/hb/Anaconda3/envs/map/lib/python3.8/site-packages/nuscenes/nuscenes.py", line 62, in __init__
    assert osp.exists(self.table_root), 'Database version not found: {}'.format(self.table_root)
AssertionError: Database version not found: /home/hb/project/MapUncertaintyPrediction/nuscenes/v1.0-mini-trainval
'Please answer, looking forward to your reply

**Comment by HB1109** [comment]
The problem has been resolved
Refer to methods if necessary
MapUncertaintyPrediction/MapTR_modified/tools/create_data.pyThe directory '/ home/hb/project/MapUncertaintyPrediction/MapTR_modified/tools/create_data. Line 927 p y' file '- trainval and delete line 936 "- the test"Thanks
