### ISSUE TITLE
Visualisation Issue 

### ISSUE THREAD

**Issue by sharmasushil** [alfredgu001324/MapUncertaintyPrediction#28]
Hi, 

Thank you for your support so far. 
I am running the visualization part:
 
cd MapTRv2_modified

python vis_std.py \
  --version mini \                                   [mini, trainval]
  --dataroot ../nuscenes \
  --split mini_val \                                 [mini_val, val]
  --trj_pred HiVT \                                  [HiVT, DenseTNT]
  --map MapTR \                                      [MapTR, StreamMapNet]
  --trj_data ../trj_data/maptr/mini_val/data \                   
  --base_results ../PATH_to_baseline_prediction_results \
  --unc_results ../PATH_to_unc_prediction_results \
  --boxes bbox.pkl \
  --save_path $SAVE_PATH

Questions:
1. When I run the above command it gives me an error:
```
Traceback (most recent call last):
  File "vis_std.py", line 533, in <module>
    main(args)
  File "vis_std.py", line 258, in main
    boxes_gt_all = pickle.load(handle)
  File "/media/xxxl/Storage/MapUncertaintyPrediction/MapTRv2_modified/projects/mmdet3d_plugin/__init__.py", line 1, in <module>
    from .core.bbox.assigners.hungarian_assigner_3d import HungarianAssigner3D
  File "/media/xxx/Storage/MapUncertaintyPrediction/MapTRv2_modified/projects/mmdet3d_plugin/core/bbox/assigners/__init__.py", line 1, in <module>
    from .hungarian_assigner_3d import HungarianAssigner3D
  File "/media/xxx/Storage/MapUncertaintyPrediction/MapTRv2_modified/projects/mmdet3d_plugin/core/bbox/assigners/hungarian_assigner_3d.py", line 3, in <module>
    from mmdet.core.bbox.builder import BBOX_ASSIGNERS
ModuleNotFoundError: No module named 'mmdet'

Which mmdet we need to install 


```
3. Where I can find the pickle file for base and unc --base_results ../PATH_to_baseline_prediction_results \
  --unc_results ../PATH_to_unc_prediction_results \

Thanks a million

**Comment by alfredgu001324** [comment]
1. Uhmm I think this is due to a missing package installation? It should be this version: https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/08baf647b8fb7d20cb2840ed8996dd788cd38f3f/requirements.txt#L86

3. These are the results from your trajectory prediction from: https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/trj.md

Basically you can follow the instructions under Visualization to save these pickle files.

Let me know if this helps!

**Comment by sharmasushil** [comment]
Thank you so much for your help. 

I fixed this issue
