### ISSUE TITLE
How to obtain Trajdata pickle files and Ground truth files?

### ISSUE THREAD

**Issue by JT-Sun** [alfredgu001324/MapUncertaintyPrediction#30]
Hello, thank you for your great work, I have a question is how to get the following documents? How do you generate and obtain these files?
Trajdata pickle files: traj_scene_frame_{full_train, full_val, mini_train, mini_val}.pkl
Ground truth files: gt_{full_train, full_val, mini_val}.pickle

**Comment by alfredgu001324** [comment]
1) This is a very good question, and it is done in a very very ugly way. So what I did is that I dig into the source code of trajdata (basically when you pip install it in the environment, you go to that specific trajdata package in the environment), and replace `data_specific/nusc/nusc_dataset.py` with the attached file. In the attached file, you can find the 'secret' to align the data back to 2Hz and map that to the corresponding sample token.
[nusc_dataset.txt](https://github.com/user-attachments/files/17783647/nusc_dataset.txt)


2) These GT are generated using MapTR's visualization script, which you can find [here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/MapTR_modified/tools/maptr/vis_pred.py). 

Hope this helps!

**Comment by JT-Sun** [comment]
This is very helpful and thank you for your quick response！  
But for the second GT files, I can't find the code that can generate the corresponding pickle in the code, so do I need to modify and add the corresponding pickle generating code in vis_std.py?

**Comment by alfredgu001324** [comment]
Yes exactly, I do not have the specific code anymore, but it should be easy to modify.

**Comment by JT-Sun** [comment]
Thanks again! With best wishes！
Also, does the code fit into other datasets like Argoversev2 or Waymo or lyft？

**Comment by alfredgu001324** [comment]
Unfortunately no at the moment, we gave a quick try for Argoverse 2. But its sensor data and motion data are not aligned as in nuScenes, where you can pair them up using sample token. (maybe we are wrong, we did not really dig too deep into it). For Waymo, I belive their sensor data is not as rich as motion data. for lyft I am not sure actually.

**Comment by JT-Sun** [comment]
Thank you very much！
best wishes！
