### ISSUE TITLE
Confusion about metrics of the map

### ISSUE THREAD

**Issue by comwireless** [alfredgu001324/MapUncertaintyPrediction#33]
Thanks for your great job. In your paper, the mAP of MapTR is 44.88, which is different from the mAP(50.3) of the official MapTR. Could you tell me what cased this difference?
![image](https://github.com/user-attachments/assets/1f1773fe-4a8e-4038-8175-460abe580e2e)

**Comment by alfredgu001324** [comment]
Hi, I am actually not sure either. But in these papers it is usually hard to reproduce the results exactly. I think I changed the learning rate and batch size etc. because my hardware setup is different from what is used by the original paper, but there might just be some stochasticity there.

**Comment by comwireless** [comment]
Get it, thank you for your reply
