### ISSUE TITLE
The training problem in "trj"

### ISSUE THREAD

**Issue by pengxuanyang** [alfredgu001324/MapUncertaintyPrediction#4]
1. I don’t know what train data is used here when I’m in the TRJ step? 
2. How is it obtained? 
3. Whether the val data used in the TRJ step is the mapping_result obtained from the mapping step?

**Comment by alfredgu001324** [comment]
1. The train data consists of two parts, estimated map and gt trj. After you train the unc map models, you use it to evaluate the train data. This will be the training data (map part) for the TRJ step. 
2. [Here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/adaptor.md) shows the merging process of estimated map data and trj data. This needs to be run for different splits: train, val, mini_train, mini_val etc. 
3. The mapping_results here is more like a placeholder name, it can be mapping_results from evaluating on the train data, or it can be mapping_results from evaluating on the val data, depending on which split you want to generate. You should run this step for a minimum of two times (i.e. to generate the train and val data). So yes, the val data used in the TRJ step is the mapping_result obtained from the mapping step by evaluating on val, the train data used in the TRJ step is the mapping_result obtained from the mapping step by evaluating on train.

**Comment by pengxuanyang** [comment]
> 1. The train data consists of two parts, estimated map and gt trj. After you train the unc map models, you use it to evaluate the train data. This will be the training data (map part) for the TRJ step.
> 2. [Here](https://github.com/alfredgu001324/MapUncertaintyPrediction/blob/main/docs/adaptor.md) shows the merging process of estimated map data and trj data. This needs to be run for different splits: train, val, mini_train, mini_val etc.
> 3. The mapping_results here is more like a placeholder name, it can be mapping_results from evaluating on the train data, or it can be mapping_results from evaluating on the val data, depending on which split you want to generate. You should run this step for a minimum of two times (i.e. to generate the train and val data). So yes, the val data used in the TRJ step is the mapping_result obtained from the mapping step by evaluating on val, the train data used in the TRJ step is the mapping_result obtained from the mapping step by evaluating on train.

Thank you for your outstanding work and your reply. Your response is exactly the answer I need to verify. I have already been trying to do this. Thank you so much!

**Comment by alfredgu001324** [comment]
No problem, thank you for pointing this out👍. I will try to update it later after CVPR
