### ISSUE TITLE
Thank you very much for your work. I ran into this problem while preprocessing the data.

### ISSUE THREAD

**Issue by BDRhm** [alfredgu001324/MapUncertaintyPrediction#8]
![Snipaste_2024-07-13_10-50-27](https://github.com/user-attachments/assets/36d9b064-c4df-4e33-8adc-c9d8be7b2ac7)

**Comment by alfredgu001324** [comment]
Thanks for reaching out! Can you post a more detailed error message? Which line is causing such problem, and which data preprocessing step is this?

**Comment by BDRhm** [comment]
> Thanks for reaching out! Can you post a more detailed error message? Which line is causing such problem, and which data preprocessing step is this?

While executing data preprocessing mapv2, the above error occurred when I executed the following command

**Comment by alfredgu001324** [comment]
I cannot see your posted command. Can you maybe double check the version of networkx installed? It should be version 2.3
