### ISSUE TITLE
Are all experiments done on a single gpu？

### ISSUE THREAD

**Issue by JT-Sun** [alfredgu001324/MapUncertaintyPrediction#9]
Thanks for your excellent work, Are all your map training and verification experiments done on a single gpu? Do you have multiple gpu versions?

**Comment by alfredgu001324** [comment]
Hi, thanks for your interest in our work! Unfortunately, I do not have a multi-GPU script. All of our experiments are done on a single GPU due to compute resource limitation. But I would encourage looking out the original repo of these works, I believe they do provide scripts for multi-GPU setting!
